DROP DATABASE IF EXISTS Restaurants;

CREATE DATABASE Restaurants;

USE Restaurants;

CREATE TABLE Address(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	City VARCHAR(50) NOT NULL,
	Street VARCHAR(50) NOT NULL,
	Postal_code VARCHAR(6) NOT NULL,
	Building_number VARCHAR(10) NOT NULL
);

CREATE TABLE Restaurant(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
	Address INT NOT NULL,
	FOREIGN KEY (Address) REFERENCES Address(id),
	Phone_number VARCHAR(15) NOT NULL
);

CREATE TABLE Restaurant_table(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Number INT NOT NULL,
	Restaurant_id INT NOT NULL,
	FOREIGN KEY (Restaurant_id) REFERENCES Restaurant(id)
);

CREATE TABLE Reservation(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Date DATE NOT NULL,
	Number_of_people INT NOT NULL,
	Restaurant_table_id INT NOT NULL,
	FOREIGN KEY (Restaurant_table_id) REFERENCES Restaurant_table(id)
);

CREATE TABLE Meal_type(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Type VARCHAR(40) NOT NULL
);

CREATE TABLE Meal(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Name VARCHAR(50) UNIQUE NOT NULL,
	Price DECIMAL NOT NULL,
	Meal_type INT NOT NULL,
	FOREIGN KEY (Meal_type) REFERENCES Meal_type(id)
);

CREATE TABLE Role(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Name VARCHAR(40) NOT NULL
);

CREATE TABLE Employee(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	First_name VARCHAR(50) NOT NULL,
	Second_name VARCHAR(50) NOT NULL,
	Pesel VARCHAR(11) NOT NULL,
	Phone_number VARCHAR(15) NOT NULL
);

CREATE TABLE Employee_role(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Role_id INT NOT NULL,
	FOREIGN KEY (Role_id) REFERENCES Role(id),
	Employee_id INT NOT NULL,
	FOREIGN KEY (Employee_id) REFERENCES Employee(id)
);

CREATE TABLE Restaurant_employee(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Restaurant_id INT NOT NULL,
	FOREIGN KEY (Restaurant_id) REFERENCES Restaurant(id),
	Employee_id INT NOT NULL,
	FOREIGN KEY (Employee_id) REFERENCES Employee(id)
);

CREATE TABLE Restaurant_meal(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Meal_id INT NOT NULL,
	FOREIGN KEY (Meal_id) REFERENCES Meal(id),
	Restaurant_id INT NOT NULL,
	FOREIGN KEY (Restaurant_id) REFERENCES Restaurant(id)
);

CREATE TABLE Account(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(50) NOT NULL,
	second_name VARCHAR(50) NOT NULL,
	phone_number VARCHAR(15) NOT NULL,
	email VARCHAR(40) NOT NULL
);

CREATE TABLE Account_bill(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Restaurant_id INT NOT NULL,
	FOREIGN KEY (Restaurant_id) REFERENCES Restaurant(id),
	Account_id INT NOT NULL,
	FOREIGN KEY (Account_id) REFERENCES Account(id),
	total_price DECIMAL NOT NULL
);

CREATE TABLE User_order(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	meal_id INT NOT NULL,
	FOREIGN KEY (meal_id) REFERENCES meal(id),
	Account_bill_id INT NOT NULL,
	FOREIGN KEY (Account_bill_id) REFERENCES Account_bill(id)
);

CREATE TABLE Dynamic_pricing(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Account_id INT NOT NULL,
	FOREIGN KEY (Account_id) REFERENCES Account(id),
	meal_id INT NOT NULL,
	FOREIGN KEY (meal_id) REFERENCES Meal(id),
	Discount FLOAT
);